title: 徒步旅行的猪
description: My Personal Blog
author: xu zhe
logo: tblxdezhu.github.io/static/img/WechatIMG1.jpeg
github: https://github.com/tblxdezhu
about: this is my kingdom.
baseurl: "https://tblxdezhu.github.io"
url: "https://tblxdezhu.github.io"

disqus_shortname: tblxdezhu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
