title: 徒步旅行的猪
description: My Personal Blog
author: 徐哲
logo: http://7xtqm4.com1.z0.glb.clouddn.com/WechatIMG1.jpeg
github: https://github.com/tblxdezhu
about: Wish you better.         
baseurl: "https://tblxdezhu.github.io"
url: "https://tblxdezhu.github.io"

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : tblxdezhu

google_analytics: UA-90420125-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: redcarpet
gems: [jekyll-paginate, jekyll-gist]
